import type { Metadata } from "next";
import { Inder } from "next/font/google";
import "./globals.css";

const inder = Inder({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-inder",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body className={`${inder.variable} darkfont-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
